bindings/python/pymongoarrow/bson.pyi, bindings/python/pymongoarrow/builders.pyi, bindings/python/pymongoarrow/context.py, bindings/python/pymongoarrow/lib.pyx, bindings/python/pymongoarrow/libbson/__init__.pxd, bindings/python/pymongoarrow/schema.py, bindings/python/pymongoarrow/types.py, bindings/python/test/test_bson.py, bindings/python/test/test_schema.py
With this PR we can now move data from a stream of BSON documents, into Arrow arrays which can then be assembled as an Arrow Table. 
This current design is inefficient because:
1. Extensive use of Python maps. Looking up entities stored in `Schema` and `PyMongoArrowContext` objecs incurs the additional overhead of calling Python functions from C. We do this every time we need to process a field from the BSON stream so it will result in very high overhead for a large number of documents/fields. Mitigation: use `std::map` instances. instead of Python dicts.
2. Use of Python APIs for Builder classes. When appending entries via the builder APIs we are using the Cython wrapper classes around Arrow's native ArrayBuilder classes. In addition to overhead of the Python function call itself, this …
=> POC implementation for converting a stream of BSON documents to a pyarrow.Table instance

bindings/python/pymongoarrow/api.py, bindings/python/test/test_pandas.py
Though the design calls for it, I think we should drop the `na_value` field because pandas has great utilities for handling missing values - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html
If we did add `na_value` support it would basically be a pass-through which doesn't make too much sense to me... It might be better handled by really good docs.
=> Public API for Pandas

bindings/python/setup.py
Motivation: explicit specification of a NumPy version was resulting in PyMongoArrow being built against a NumPy version different than what PyArrow was being built against. This resulted in the following warning at runtime:
```
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
```
=> Cleanup setup.py

bindings/python/setup.py
Modify `setup.py` to pick up `libbson` even when `LIBBSON_INSTALL_DIR` is unset but when `libbson` is discoverable via `pkg-config`.
=> Modify setup.py such that it can detect libbson installed in standard locations

bindings/python/benchmark.py, bindings/python/pymongoarrow/api.py, bindings/python/pymongoarrow/bson.pyi, bindings/python/pymongoarrow/builders.pyi, bindings/python/pymongoarrow/context.py, bindings/python/pymongoarrow/lib.pyx
Adapted from https://github.com/mongodb/bson-numpy/blob/c0bacea/benchmark.py
Here's the benchmark output on my machine before the optimizations:
```
100000 small docs, 40 bytes each with 3 keys
1000 large docs, 153k each with 2600 keys
BENCH:   SMALL   LARGE
conventional-to-ndarray:    0.27    1.13
pymongoarrow-to-numpy:    0.14    2.36
conventional-to-pandas:    0.35    1.69
pymongoarrow-to-pandas:    0.14    2.41
pymongoarrow-to-arrow:    0.14    2.35
```
And here is the improved output:
```
100000 small docs, 40 bytes each with 3 keys
1000 large docs, 153k each with 2600 keys
BENCH:   SMALL   LARGE
conventional-to-ndarray:    0.27    1.17
pymongoarrow-to-numpy:    0.10    1.25
conventional-to-pandas:    0.36    1.82
pymongoarrow-to-pandas:    0.10    1.32
pymongoarrow-to-arrow:    0.10 …
```
=> PYTHON-2497 Add benchmark adapted from bson-numpy and increase perf by 50%

bindings/python/setup.py
I noticed this when `python setup.py check` ran as a part of `python setup.py sdist` and produced the following output:
```
running check
warning: check: missing required meta-data: url
```
I don't think it affects any functionality but obviously we need to fix it.
=> Add required metadata field URL to setup.py

.github/workflows/test-python.yml, bindings/python/.gitignore, bindings/python/MANIFEST.in, bindings/python/docs/source/developer/installation.rst, bindings/python/pymongoarrow/__init__.py, bindings/python/pyproject.toml, bindings/python/release.sh, bindings/python/requirements/build.txt, bindings/python/requirements/test.txt, bindings/python/setup.cfg, bindings/python/setup.py
=> PYTHON-3047 Clean up handling of pyarrow library

bindings/python/benchmark.py, bindings/python/pymongoarrow/api.py, bindings/python/pymongoarrow/types.py, bindings/python/test/test_pandas.py
```
100000 small docs, 40 bytes each with 3 keys
1000 large docs, 153k each with 2600 keys
BENCH:   SMALL   LARGE
insert_pandas:    1.88    4.94 
```
=> ARROW-73 Add support and testing for Pandas

bindings/python/benchmark.py, bindings/python/pymongoarrow/api.py, bindings/python/pymongoarrow/types.py, bindings/python/test/test_arrow.py, bindings/python/test/test_numpy.py, bindings/python/test/test_pandas.py
Benchmark results:
```
(python3.8) ➜  python git:(ARROW-74) ✗ python benchmark.py
100000 small docs, 40 bytes each with 3 keys
1000 large docs, 153k each with 2600 keys
BENCH:   SMALL   LARGE
conventional-to-ndarray:    0.20    1.13 
pymongoarrow-to-numpy:    0.29    1.69 
conventional-to-pandas:    0.26    1.74 
pymongoarrow-to-pandas:    0.28    1.67 
pymongoarrow-to-arrow:    0.28    1.67 
insert_arrow:    1.79    4.78 
insert_conventional:    1.86    4.86 
insert_pandas:    2.24    5.04 
insert_numpy:    2.15    4.66 
```
=> ARROW-74 Add support and testing for NumPy

bindings/python/test/test_arrow.py, bindings/python/test/test_numpy.py, bindings/python/test/test_pandas.py, bindings/python/test/utils.py
Adds unit tests for null value behaviors for pyarrow, numpy, and pandas. Leaves underlying behavior intact.
=> ARROW-94 Test for nulls

.github/workflows/benchmark.yml
The old pip install -vvv output spits out 10000 lines of output which makes it hard to view the actual benchmark results.
=> Make the benchmark results more readable

.github/workflows/benchmark.yml
The benchmark runs much faster on ubuntu-22.04 (~5min) vs macOS (~10-15min).
=> Migrate benchmark tests to ubuntu-22.04

.github/workflows/benchmark.yml, bindings/python/asv.conf.json, bindings/python/benchmarks/benchmarks.py
The switch from setup to setup_cache was motivated by the fact that `peakmem` takes `setup` into account when calculating memory, which we do not want.
=> ARROW-147 Update benchmark tests to include memory usage

bindings/python/pymongoarrow/lib.pyx, bindings/python/test/test_arrow.py
https://jira.mongodb.org/browse/ARROW-158
This fixes the bug in [#136](https://github.com/mongodb-labs/mongo-arrow/issues/136) by properly handling the case where a list or document is empty. When an empty or null list or document is encountered, we skip to examining the next document.
The TODOs are related to how we call append_null() to "backfill" previous records once we discover the schema. Our schema detection differs from pyarrow's from_pylist detection. An example of the difference is in test_auto_schema_first_embedded_list_null:
```
test/test_arrow.py::TestArrowExplicitApi::test_auto_schema_first_embedded_list_null
Expected: pyarrow.Table
a: struct<b: list<item: string>>
child 0, b: list<item: string>
child 0, item: string
----
a: [
-- is_valid: all not null
-- child 0 type: …
```
=> ARROW-158 Fix crash when performing auto schema detection on embedded lists and subdocuments

bindings/python/README.md, bindings/python/pyproject.toml
Also updates the Project [URLs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls) that will be rendered on PyPI since we're removing a couple links from the readme.
=> ARROW-196 Add badges to README

bindings/python/pymongoarrow/__init__.py, bindings/python/pyproject.toml
The check for a compatible lib_bson version done in `bindings/python/pymongoarrow/_init_.py` throws a DeprecationWarning. This is preventing [PR](https://github.com/mongodb-labs/mongo-arrow/pull/186) for [ARROW-200](https://jira.mongodb.org/browse/ARROW-200) to be merged.
I've cherry-picked the commit from that PR's branch and opened this new one.
=> [ARROW-208] Replaced deprecated pkg_resource with packaging.version

bindings/python/pymongoarrow/context.py, bindings/python/pymongoarrow/lib.pyx, bindings/python/pymongoarrow/schema.py, bindings/python/pymongoarrow/types.py, bindings/python/test/test_arrow.py, bindings/python/test/test_datetime.py
Adding support for two additional Arrow DataTypes: `large_list` and `large_string` appear in the `Table.schema` when one calls `Polars to_arrow`.
This is a small extension of our ListBuilder and StringBuilder classes and additional tests,
=> [ARROW-210] Add support for large_list and large_string PyArrow DataTypes

README.md
quick clarifying question if i may: is this library solely concerned with reading? it does not handle `numpy` type conversion to BSON on DB write?
context: it appears `numpy.bool_` fails to BSON-serialize with numpy v2 https://github.com/materialsproject/fireworks/issues/522
=> Code fence syntax highlight in readme

bindings/python/pymongoarrow/types.py, bindings/python/test/test_schema.py
[JIRA TICKET](https://jira.mongodb.org/browse/ARROW-241)
=> ARROW-241: Checking list-types in schema support raises an error

bindings/python/pymongoarrow/api.py, bindings/python/test/test_polars.py
Hi,
_arrow_to_polars currently has no support to cast extension types for nested fields. 
This prohibits ObjectIDs to be read in case they are in nested fields.
I could not manage the conversion with the original code, 
but I found a way to using `arrow_table_without_extensions = arrow_table.cast(schema_without_extensions)` 
to cast the schema of the whole table in one go.
The schema_without_extensions is created recursively from the old schema.
Support for lists is still to be added, should not be that hard, maybe I try tomorrow.
I am not an expert in apache arrow. My world is Pandas and Polars.
I have wrote some unit tests locally to test the code, but I do not feel confident that I have not overlooked
something, so please review carefully. 
#219
=> Support for nested ObjectIDs in polars conversion

.github/workflows/release-python.yml, .github/workflows/test-python.yml, bindings/python/CHANGELOG.md, bindings/python/CONTRIBUTING.md, bindings/python/pymongoarrow/api.py, bindings/python/pymongoarrow/pandas_types.py, bindings/python/pyproject.toml, bindings/python/test/test_arrow.py, bindings/python/test/test_builders.py, bindings/python/test/test_datetime.py, bindings/python/test/test_numpy.py, bindings/python/test/test_pandas.py, bindings/python/test/test_polars.py, bindings/python/test/test_pymongoarrow.py
- Ensure clients are closed
- Address polars test failures
- Drop Python 3.8 support
=> ARROW-255 Update test config and address test failures

.github/workflows/release-python.yml, bindings/python/pymongoarrow/lib.pyx, bindings/python/test/test_arrow.py
https://jira.mongodb.org/browse/INTPYTHON-490
Fixes #260
=> INTPYTHON-490 Fix segmentation fault when document doesn't match schema

.github/workflows/release-python.yml
Also use the new native `ubuntu-20.04-arm64` instead of relying on QEMU.
=>  PYTHON-5058 & PYTHON-5047 Improve testing of publish workflows

bindings/python/pymongoarrow/lib.pyx, bindings/python/test/test_arrow.py
=> INTPYTHON-498 Missing field handling in nested data

bindings/python/pymongoarrow/schema.py, bindings/python/test/test_arrow.py, bindings/python/test/test_schema.py, bindings/python/tox.ini
see https://github.com/mongodb-labs/mongo-arrow/issues/284
=> INTPYTHON-549 Rework the projection logic to allow reading list-of-struct data structures using a specified schema

.github/workflows/dist-python.yml, .github/workflows/release-python.yml, bindings/python/RELEASE.md
Depends on https://github.com/mongodb-labs/drivers-github-tools/pull/78 (merged)
Successful run: https://github.com/mongodb-labs/mongo-arrow/actions/runs/14495783723
=> INTPYTHON-589 Add automated release support for pymongoarrow

.github/workflows/test-python.yml, bindings/python/CHANGELOG.md, bindings/python/justfile, bindings/python/pymongoarrow/api.py, bindings/python/pymongoarrow/pandas_types.py, bindings/python/pyproject.toml, bindings/python/test/conftest.py, bindings/python/test/pandas_types/test_binary.py, bindings/python/test/pandas_types/test_code.py, bindings/python/test/pandas_types/test_decimal128.py, bindings/python/test/pandas_types/test_objectid.py, bindings/python/test/test_numpy.py, bindings/python/test/test_pandas.py, bindings/python/test/test_pymongoarrow.py, bindings/python/test/utils.py, bindings/python/uv.lock
=> INTPYTHON-653 & INTPYTHON-620 Make pandas optional and add free-threading support on Windows

.github/workflows/test-python.yml, bindings/python/CONTRIBUTING.md, bindings/python/setup.py
=> INTPYTHON-665 Add support for bson2

bindings/python/pymongoarrow/api.py, bindings/python/test/test_arrow.py
I think this is what we want??? 
edit: docs will be completed via a docs ticket but in general the only parquet types that we don't inherently already support are on the left and what they can be converted to (that we do support) are on the right. 
- uint8 -> pa.int32
- uint16 -> pa.int32
- uint32 -> pa.int64
- uint64 -> pa.int64
- int8 -> pa.int32
- int16 -> pa.int32
- float16 -> pa.float64
- float32 -> pa.float64
- float64 -> pa.float64
- timedelta -> pa.int64
=> INTPYTHON-520 Ensure all parquet data types are handled
